### ISSUE TITLE
大佬，请问高分辨屏幕怎么修改界面DPI大小

### ISSUE THREAD

**Issue by XAVIER2020-CLOUD** [xuthus5/fedora-packager#11]
大佬，请问高分辨屏幕怎么修改界面DPI大小，WINEPREFIX=~/.deepinwine/Deepin-WeChat /usr/bin/deepin-wine6-stable winecfg修改后不起作用

**Comment by xuthus5** [comment]
删除WINEPREFIX目录重启微信试一下？

**Comment by XAVIER2020-CLOUD** [comment]
[> [yangcn@fedora ~]$ WINEPREFIX=~/.deepinwine/Deepin-WeChat /usr/bin/deepin-wine6-stable winecfg
/usr/bin/deepin-wine6-stable: 第 45 行：68322 段错误               （核心已转储）WINEPREFIX=$wineprefix WINELOADER=$wineloader WINEDEBUG=$winedebug $wine "$@"
[yangcn@fedora ~]$ sudo WINEPREFIX=~/.deepinwine/Deepin-WeChat /usr/bin/deepin-wine6-stable winecfg
[sudo] yangcn 的密码：
wine: '/home/yangcn/.deepinwine/Deepin-WeChat' is not owned by you
[yangcn@fedora ~]$ sudo su
[root@fedora yangcn]# WINEPREFIX=~/.deepinwine/Deepin-WeChat /usr/bin/deepin-wine6-stable winecfg
wine version: 6.0
[root@fedora yangcn]# exit
exit](

> url

)

**Comment by XAVIER2020-CLOUD** [comment]
> 删除WINEPREFIX目录重启微信试一下？

不进入sudo su 有错误：
```
[yangcn@fedora ~]$ WINEPREFIX=~/.deepinwine/Deepin-WeChat /usr/bin/deepin-wine6-stable winecfg
/usr/bin/deepin-wine6-stable: 第 45 行：68322 段错误               （核心已转储）WINEPREFIX=$wineprefix WINELOADER=$wineloader WINEDEBUG=$winedebug $wine "$@"

[yangcn@fedora ~]$ sudo WINEPREFIX=~/.deepinwine/Deepin-WeChat /usr/bin/deepin-wine6-stable winecfg
[sudo] yangcn 的密码：
wine: '/home/yangcn/.deepinwine/Deepin-WeChat' is not owned by you
```

sudo su 可以打开配置页面但是改了不起作用：
```
[yangcn@fedora ~]$ sudo su
[root@fedora yangcn]# WINEPREFIX=~/.deepinwine/Deepin-WeChat /usr/bin/deepin-wine6-stable winecfg
wine version: 6.0
[root@fedora yangcn]# exit
exit
```

**Comment by xuthus5** [comment]
> 

sudo 后用户已经切换了。

**Comment by XAVIER2020-CLOUD** [comment]
> $ WINEPREFIX=~/.deepinwine/Deepin-WeChat /usr/bin/deepin-wine6-stable winecfg
> /usr/bin/deepin-wine6-stable: 第 45 行：68322 段错误               （核心已转储）WINEPREFIX=$wineprefix WINELOADER=$wineloader WINEDEBUG=$winedebug $wine "$@"

好像系统的lib问题，自己系统的和该项目打包的不一样，小白放弃了

**Comment by XAVIER2020-CLOUD** [comment]
> 居然搜到了办法：
https://github.com/vufa/deepin-wine-wechat-arch/issues/173
```
在/etc/environment文件(全局配置，对所有用户生效，修改需要root权限)或~/.pam_environment(没有可以创建一个，无需root权限，仅对当前用户生效)添加一行:
DEEPIN_WINE_SCALE=1.25
```
