### ISSUE TITLE
WinChatWin.dll errCode:126

### ISSUE THREAD

**Issue by xsh005** [xuthus5/fedora-packager#13]
wine报错：
0110:err:module:import_dll Library WLDAP32.dll (which is needed by L"C:\\Program Files (x86)\\Tencent\\WeChat\\[3.9.2.23]\\WeChatWin.dll") not found

reproduce:
```
sudo dnf config-manager --add-repo https://download.opensuse.org/repositories/home:xuthus5/Fedora_37/home:xuthus5.repo
sudo dnf install fedora-deepin-wine6 fedora-deepin-wine-helper -y
sudo dnf install fedora-deepin-wechat-wine6 -y
```
OS: Fedora 38
和我用原生wine试图运行的报错是一样的...已经装了cjkfonts和riched20,winecfg里添加wldap32依赖也无法解决，求大佬支个招

**Comment by xuthus5** [comment]
参考 **WechatWin.dll文件缺失** 章节

**Comment by xsh005** [comment]
谢谢！现在可以完美运行了，之前试了太久破防了就没认真看doc，感谢佬维护这个repo！
