### ISSUE TITLE
Fedora38支持

### ISSUE THREAD

**Issue by zhcong** [xuthus5/fedora-packager#14]
你好，请问有支持fedora38的计划吗？

**Comment by xuthus5** [comment]
**好的，我支持一下**

**Comment by xuthus5** [comment]
已支持

**Comment by curry798** [comment]
@xuthus5 
在 fedora 38 上使用 wine 6无法启动企业微信（微信可以启动）
![图片](https://github.com/xuthus5/fedora-packager/assets/112856271/911dc206-d8cd-4aa5-b52e-e49493cdc304)

**Comment by xuthus5** [comment]
> @xuthus5 在 fedora 38 上使用 wine 6无法启动企业微信（微信可以启动） ![图片](https://user-images.githubusercontent.com/112856271/279553791-911dc206-d8cd-4aa5-b52e-e49493cdc304.png)

请按该章节，提供一下DEBUG日志：
https://github.com/xuthus5/fedora-packager#%E6%88%91%E6%97%A0%E6%B3%95%E8%BF%90%E8%A1%8C%E8%BD%AF%E4%BB%B6-%E4%B9%9F%E6%97%A0%E6%B3%95%E6%8B%BF%E5%88%B0%E8%BF%90%E8%A1%8C%E6%97%A5%E5%BF%97

**Comment by curry798** [comment]
> > @xuthus5 在 fedora 38 上使用 wine 6无法启动企业微信（微信可以启动） ![图片](https://user-images.githubusercontent.com/112856271/279553791-911dc206-d8cd-4aa5-b52e-e49493cdc304.png)
> 
> 请按该章节，提供一下DEBUG日志： https://github.com/xuthus5/fedora-packager#%E6%88%91%E6%97%A0%E6%B3%95%E8%BF%90%E8%A1%8C%E8%BD%AF%E4%BB%B6-%E4%B9%9F%E6%97%A0%E6%B3%95%E6%8B%BF%E5%88%B0%E8%BF%90%E8%A1%8C%E6%97%A5%E5%BF%97

感谢你的回复，我已经解决了这一个问题 -- 使用 wine 8 可以启动
