### ISSUE TITLE
无法下载所需dll.so文件

### ISSUE THREAD

**Issue by josephmahede** [xuthus5/fedora-packager#15]
`sudo wget -O wldap32.dll.so https://images.xuthus.cc/images/akrHXou_wldap32.dll.so
--2023-06-06 14:16:12--  https://images.xuthus.cc/images/akrHXou_wldap32.dll.so
Resolving images.xuthus.cc (images.xuthus.cc)... 240e:95c:3004:a:800::38, 240e:974:eb00:201::a2, 61.139.65.249
Connecting to images.xuthus.cc (images.xuthus.cc)|240e:95c:3004:a:800::38|:443... failed: Connection timed out.
Connecting to images.xuthus.cc (images.xuthus.cc)|240e:974:eb00:201::a2|:443... 
`

**Comment by xuthus5** [comment]
目前未遇到问题。请重试或切换网络环境。
