### ISSUE TITLE
安装wechat-wine6所需的部分文件无法下载

### ISSUE THREAD

**Issue by plasmetoz** [xuthus5/fedora-packager#6]
系统为fedora 36，按照教程安装fedora-deepin-wine6 fedora-deepin-wine-helper fedora-deepin-wine6后启动报无效WeChatWin.dll 126错误，现在正在安装教程进行修补，但是执行 wget -O wldap32.dll.so https://images.xuthus.cc/images/akrHXou_wldap32.dll.so 失败。
![截屏-20220715093739-634x130](https://user-images.githubusercontent.com/21010914/179129954-b8e1e4e4-b3fb-471c-ae5b-706436e17534.png)
![截屏-20220715093724-1281x299](https://user-images.githubusercontent.com/21010914/179129962-c24011f1-4c5b-4abc-863d-c31c15f912b1.png)

**Comment by plasmetoz** [comment]
附：
 fedora-deepin-extra-lib-0.0.1-2.1.x86_64.rpm安装及相关软连接已完成
deepin相关包安装情况： 
![截屏-20220715094344-860x436](https://user-images.githubusercontent.com/21010914/179130163-8325c1c7-925d-4bf0-8b8b-a71ac46beee0.png)

**Comment by xuthus5** [comment]
系存储系统欠费所致,现已正常。
