### ISSUE TITLE
Fedora 36下无法安装微信，错误如下

### ISSUE THREAD

**Issue by MicroHanqi** [xuthus5/fedora-packager#7]
┬─[wilson@192:~]─[11时04分36秒]
╰─>$ sudo dnf install fedora-deepin-wechat -y
上次元数据过期检查：0:26:03 前，执行于 2022年08月27日 星期六 10时38分49秒。
错误：
 问题: 软件包 fedora-deepin-wechat-3.7.0-8.1.x86_64 需要 fedora-deepin-wine5，但没有提供者可以被安装
  - 冲突的请求
  - 没有东西可提供 libpcap.so.0.8（fedora-deepin-wine5-5.0.16-6.1.x86_64 需要）
(尝试添加 '--skip-broken' 来跳过无法安装的软件包)

**Comment by xuthus5** [comment]
fedora36请使用wine6版本
