### ISSUE TITLE
微信在打开文件选择弹窗时会直接崩溃

### ISSUE THREAD

**Issue by plasmetoz** [xuthus5/fedora-packager#8]
系统为fedora 36，在据现在1-2个月的软件包更新（也可能因为其他原因）后在微信中任何打开文件选择框的操作会导致微信崩溃。但是从外面推拽文件进来似乎没有问题。
使用Wayland。
可能相关的报错信息：

<pre>[xcb] Unknown sequence number while processing queue
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
xcb_io.c:269：poll_for_event: 假设 ‘!xcb_xlib_threads_sequence_lost’ 失败。
03ec:fixme:heap:RtlSetHeapInformation 00000000 1 00000000 0 stub
</pre>
[fulllog.txt](https://github.com/xuthus5/fedora-packager/files/9856711/fulllog.txt)
[systemandrpm.txt](https://github.com/xuthus5/fedora-packager/files/9856712/systemandrpm.txt)
[WeChat573fc15.txt](https://github.com/xuthus5/fedora-packager/files/9856713/WeChat573fc15.txt)
[WeChat573fc15FMD5.txt](https://github.com/xuthus5/fedora-packager/files/9856715/WeChat573fc15FMD5.txt)

**Comment by XGZepto** [comment]
Fedora 37 + Gnome 43.3
問題依舊存在

**Comment by plasmetoz** [comment]
在最新版的run.sh 中加入 
GDK_BACKEND=x11
export GDK_BACKEND=x11
似乎可以规避这个问题，带来的副作用待确认

系统fedora 37 ，内核6.1.12-200.fc37.x86_64
相关组件版本
edora-deepin-wine-helper-5.1.27-3.1.x86_64
fedora-deepin-wine6-6.0.0.19-8.1.x86_64
fedora-deepin-extra-lib-0.0.1-7.1.x86_64
fedora-deepin-wechat-wine6-3.9.0-1.1.x86_64

**Comment by plasmetoz** [comment]
除部分表情包下可能崩溃外无异常，问题关闭
